<a href="https://colab.research.google.com/github/cbwid/practialAI/blob/main/notebook/07_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

在这节课中，我们将学习PyTorch，它是一个用于构建动态神经网络的学习库。我们将在本课程中了解其基础知识，以及如何创建和使用张量（Tensor），而我们将在下一课中使用它制作模型。

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/pytorch.png" width=300>

# Tensor 基础知识

In [2]:
# 安装PyTorch库
!pip3 install torch

>  注意：上述安装PyTorch的方式与官网并不一致，因为这里是基于Colab云端安装的，而大家一般是使用pip或者conda来安装PyTorch。具体安装教程参考：https://pytorch.org/

In [3]:
import numpy as np
import torch

**张量(Tensor)：**张量如同数组和矩阵一样，是一种特殊的数据结构，在pytorch中，神经网络的输入、输出以及网络的参数等数据，都是使用张量来进行描述的

张量的使用和中numpy的ndarrays很类似，区别在于张量可以在gpu上或者其他专用硬件上运行，这样可以得到更快的加速效果

In [4]:
# 创建一个张量
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[-3.6462e-38,  3.0756e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  3.0756e-41,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])


In [5]:
# 创建一个随机张量
x = torch.randn(2, 3) # torch.randn对应于正态分布，而rand(2,3)对应于均匀分布
print (x)

tensor([[-1.0198,  2.1064, -2.1692],
        [-0.3814,  0.0942,  0.5195]])


In [6]:
# 0和1张量
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# 列表（List） → 张量
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
# NumPy 数组 → 张量
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.4976, 0.9920, 0.0452],
        [0.0426, 0.3398, 0.2478]], dtype=torch.float64)


In [9]:
# 张量 → 数组
t=torch.ones(5)
print(f't:{t}')
n=t.numpy()
print(f'n:{n}')

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


张量和Numpy array数组在CPU上可以公用一块内存区域，改变其中一个另一个也会随之改变

In [10]:
# 修改张量的值
t.add_(1)
print(f't:{t}')
print(f'n:{n}')

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [11]:
# 修改numpy array数组的值
np.add(n,1,out=n)
print(f't:{t}')
print(f'n:{n}')

t:tensor([3., 3., 3., 3., 3.])
n:[3. 3. 3. 3. 3.]


In [12]:
# 改变张量类型（张量默认为float类型）
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor 运算

In [13]:
# 加法 + 
x = torch.randn(2, 3)
print('x.values:\n{}'.format(x))
y = torch.randn(2, 3)
print('y.values:\n{}'.format(y))

z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

x.values:
tensor([[ 0.4581, -1.3014,  1.3333],
        [ 1.0540, -0.3632, -0.9469]])
y.values:
tensor([[-1.9857,  0.1520,  1.0433],
        [ 0.3477, -1.5842,  0.0878]])
Size: torch.Size([2, 3])
Values: 
tensor([[-1.5276, -1.1495,  2.3766],
        [ 1.4017, -1.9474, -0.8590]])


In [14]:
# 向量点积:torch.mm
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 0.5134, -0.4282],
        [-1.8734,  1.1644]])


In [15]:
# 转置 torch.t()
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.5080, -0.1279,  0.2345],
        [ 1.4296,  0.5443,  0.1609]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.5080,  1.4296],
        [-0.1279,  0.5443],
        [ 0.2345,  0.1609]])


In [16]:
# Reshape 重新修改张量的维数，要保证数据的个数不变
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.5080, -0.1279],
        [ 0.2345,  1.4296],
        [ 0.5443,  0.1609]])


In [17]:
# reshaping的危险（意外后果）
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(0), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([2, 12])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3],
        [10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


```
x=x.view(batchsize,-1)
```
中batchsize指转换后有几行，而-1指在不告诉函数有多少列的情况下，根据元tensor数据和batchsize自动分配列数

torch.transpose()是pytorch种的ndarray矩阵进行转置的操作

**transpose（）一次只能在两个维度间进行转换**




In [18]:
# 维度操作
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # 为每列添加各行叠加的值
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # 为每行添加各列叠加的值
print("Values: \n{}".format(z))

Values: 
tensor([[-1.2452,  1.9658,  0.1848],
        [-0.2633, -0.2246, -1.1903]])
Values: 
tensor([-1.5085,  1.7412, -1.0055])
Values: 
tensor([ 0.9054, -1.6782])


# 索引，切片和级联

In [19]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 0.0303,  0.5724,  1.2252,  2.8963],
        [ 0.3207, -0.2938, -0.4594, -0.3912],
        [-0.0600, -1.7827,  0.8529, -0.3764]])
x[:1]: 
tensor([[0.0303, 0.5724, 1.2252, 2.8963]])
x[:1, 1:3]: 
tensor([[0.5724, 1.2252]])


In [20]:
# 选择维度索引
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # 第0和第2列的值
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # 来自（0,0）和（2,1）的值
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[-1.8211, -0.8792, -0.3720],
        [ 0.1816, -0.3371, -0.2989]])
Values: 
tensor([[-1.8211, -0.3720],
        [ 0.1816, -0.2989]])
Values: 
tensor([-1.8211, -0.2989])


In [21]:
# 级联 将两个张量拼接在一起
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # 按行堆叠（dim = 1按列堆叠）
print("Values: \n{}".format(y))

Values: 
tensor([[ 0.7832, -0.1492, -1.1440],
        [ 1.1207,  0.7086, -1.9062]])
Values: 
tensor([[ 0.7832, -0.1492, -1.1440],
        [ 1.1207,  0.7086, -1.9062],
        [ 0.7832, -0.1492, -1.1440],
        [ 1.1207,  0.7086, -1.9062]])


# 梯度

In [22]:
# 带有gradient bookkeeping的张量
# requires_grad：用于说明当前是否需要为这个张量计算梯度
# 如果一个张量的requires_grad=True，并不意味着这个张量的梯度属性会一直被存储。
# 只有当张量为叶子节点的时候，梯度财会一直保存在grad属性中，对于非叶子节点，在计算完叶子节点后就会被释放掉
# backward：反向传播计算梯度
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z是标量
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.7468, 0.6508, 0.5351, 0.0567],
        [0.2301, 0.9529, 0.9215, 0.2108],
        [0.7477, 0.9642, 0.1991, 0.2112]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(z)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

**叶子节点：不依赖其他tensor的tensor**
在pytorch中，神经网络层的权值w的tensor均为叶子节点，自己定义的tensor，例如：a=torch,tensor([1,0])定义的节点是叶子节点。但如果出现b=a+1的情况，*b也为叶子节点*，原因是：单纯的从数值关系上来看，b确实依赖a，但是从pytorch来看，所有的计算都是为了反向求导，而a的requires_grad属性为False，不需要获得梯度，那么在反向传播的过程中也是‘无意义’的，因此b为叶子节点

# 属性

In [24]:
# 从张量属性我们可以得出张量的维数、数据类型以及他们所存储的设备（CPU或GPU）
x=torch.rand(3,4)
print(f"Shape of tensor: {x.shape}")
print(f"Datatype of tensor: {x.dtype}")
print(f"Device tensor is stored on: {x.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# CUDA 张量

In [26]:
# CUDA可用吗？
print (torch.cuda.is_available())

True


如果上面的代码返回False，那么请转到菜单栏上的`Runtime`→`Change runtime type`并在`Hardware accelerator`下选择`GPU`。

In [27]:
# 创建一个CPU版的0张量
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [28]:
# 创建一个CUDA版的0张量
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
